### ISSUE TITLE
Can you elaborate on how to create an R package on GitHub?

### ISSUE THREAD

**Issue by MikkelVembye** [DrMattG/Workshop-3-Collaborative-coding-version-control-introduction-to-Git-GitHub#15]

**Comment by DrMattG** [comment]
Hi @MikkelVembye Yes - I will - I just have to feed the dog and walk her but I will come back to you later on if that's okay?

**Comment by DrMattG** [comment]
So an R package is "just" a collection of functions - it could just be one single function - with some "structures" in place to create a package - these extra structures are, for example a namespace, description, etc. You can create an R package in RStudio quite easily (see https://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/; and https://r-pkgs.org/index.html). Using GitHub you can store the code for your package using version control. Many people will submit a package to CRAN (https://cran.r-project.org/) which is a stable repository for packages - but you can also store your pacakge on GitHub and users can access it directly using the devtools or remotes packages (e.g. remotes::install_github()). 

Does this answer your question?

**Comment by MikkelVembye** [comment]
Thanks, Matt. Did not expect to get any reply. So truly thanks.

I am about to build my/our first package (have worked on in for two day
only, so I am entirely green) regarding power analysis for meta-analysis of
dependent effect sizes as Terri mentioned in her talk
https://osf.io/preprints/metaarxiv/6tp9y/

I have so far managed to make some parts of the package locally, and my
question was how to push/get the package on GitHub. What I did now was to
create a repository with the package name without making licence, README or
gitnore files, and then pull that repo and paste the package files and
folders to the repo and push it back to GitHub. Is this a reasonable way to
do it? Furthermore, my question was also related to how the
devtools::create_package function and GitHub work together. Would you
recommend making the repository first and then use the create_package when
you have pulled the repo or use the create_package function and then push
the package files and folders to the repository. I don't know if my
question makes sense. Hope you somehow get it.

Sincerely,
Mikkel

Den tir. 22. feb. 2022 kl. 21.23 skrev Matthew Grainger <
***@***.***>:

**Comment by DrMattG** [comment]
Hi Mikkel,
I think I would set up the package first in Rstudio (using devtools::create_package if you want) in a RStudio project (make sure you click on the project options and select git). Then you will need to set up your GitHub repo without READme etc and you can see the option to push up from an existing repository. It gives you two shell commands. If you copy these and paste them in the shell in the Git panel in RStudio and run them you will connect to the GitHub repo. I find that you often get an error at this stage but all you need to do is make your first commit and then pull and push. Let me know if I can help further. It looks like an interesting preprint - I am looking forward to reading it!

**Comment by MikkelVembye** [comment]
Thanks, Matt. Please, let me know if have any comments to the paper. :)

Mikkel

ons. 23. feb. 2022 kl. 10.36 skrev Matthew Grainger <
***@***.***>:
