### ISSUE TITLE
Some Issue

### ISSUE THREAD

**Issue by Tatienne-r** [DrMattG/Workshop-3-Collaborative-coding-version-control-introduction-to-Git-GitHub#9]
How do I delete a fork after I am done with it?

**Comment by DrMattG** [comment]
Go to the settings and at the bottom there is a red box labelled something like "Danger Zone". You can delete it from there by following the instructions (it normally asks you to write the name of the repository and then confirm with your password). Let me know if that works for you

**Comment by Tatienne-r** [comment]
Thank you! That worked for me. Thanks again for the workshop.
